### ISSUE TITLE
Title barely visible when defined  in YAML preambule

### ISSUE THREAD

**Issue by danieltomasz** [jegornagel/zettlr-sublime#1]
Hi!

Great looking  theme, and also good for productivity ! One thing I noticed is the title that is barely visible when defined in YAML preamble

![image](https://user-images.githubusercontent.com/7980381/104034878-c03a6800-51d1-11eb-94ab-b876ef13fb50.png)

I am on MacOS 11.1 and Zettlr 1.8.5

**Comment by jegornagel** [comment]
Fixed this in a new [CSS update](https://github.com/jegornagel/zettlr-sublime/blob/main/theme.css#L122). You can take new theme code from repository.

 Thank you for sharing this bug. I don't use YAML, so I could not know about the issue.

![image](https://user-images.githubusercontent.com/58973132/104051652-21256880-51f1-11eb-8d24-9d7f5704dca7.png)

**Comment by danieltomasz** [comment]
@jegornagel  thanks for fixing both issues  so fast! I also doesn't use yaml with headers, but Zettlr is shipping by default with those example files that contain YAML header
