### ISSUE TITLE
Filenames in subfolders aren't readable

### ISSUE THREAD

**Issue by danieltomasz** [jegornagel/zettlr-sublime#2]
The name of files in subfolders aren't looking good, I don't know if is the issue with this theme or how Zettle handle displaying it, but I am letting you know, probably solving that  would involve refactoring how Zettlr render CSS from different themes
![image](https://user-images.githubusercontent.com/7980381/104038237-3be9e400-51d5-11eb-9022-ca30fc647f1a.png)

Again MacOS 11.1 and Zettlr 1.8.5

**Comment by jegornagel** [comment]
Hi! Thank you for taking action! I fixed this by adding [a line height](https://github.com/jegornagel/zettlr-sublime/blob/main/theme.css#L34) to subfolders. Now it should work. You can grab a new code in a repository.
